### ISSUE TITLE
ジャン×ジャンクのロゴの作成

### ISSUE THREAD

**Issue by hirokikondo86** [SD22-team/raugh#20]
# ジャン×ジャンクのロゴの作成
現状はHTML, CSSで文字と画像を調整して作成している。 

(例)
<img width="213" alt="スクリーンショット 2019-12-03 21 44 20" src="https://user-images.githubusercontent.com/50824354/70052253-3f945a00-1616-11ea-9ec5-8460c092feca.png">

## 修正内容
これを一つにまとめたロゴの作成お願いします。
また、いい感じのFont Familyでお願いします。

## 要件
作成完了後はimgフォルダに logo.拡張子 として保存して下さい。

**Comment by seiya12** [comment]
![freefont_logo_GN-KillGothic](https://user-images.githubusercontent.com/51153166/70211725-23f59480-1779-11ea-8fc4-0d78a6d5b4d3.png)

フォントこれどうですか

**Comment by hirokikondo86** [comment]
無茶苦茶いいと思います！それで作成お願いしていいですか？
